# Constants
SECOND = 1000

PREDICTION_AREA_LINE_COLOR = (0, 0, 255)
PREDICTION_AREA_LINE_THICKNESS = 3

LAST_DETECTION_LINE_COLOR = (255, 0, 0)
LAST_DETECTION_LINE_THICKNESS = 3

ESTIMATION_LINE_COLOR = (0, 255, 0)
ESTIMATION_LINE_THICKNESS = 3

REAL_TIME_ESTIMATION_LINE_COLOR = (255, 255, 255)
REAL_TIME_ESTIMATION_LINE_THICKNESS = 3
